openapi: 3.0.3
info:
  title: CodeReady Dependency Analytics API
  description: Vulnerability analysis with Red Hat CodeReady Dependency Analytics
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 3.0.0
servers:
- url: http://crda-backend-crda.apps.sssc-cl01.appeng.rhecoeng.com/api/v3/
  description: Production server
- url: http://localhost:8080/api/v3/
  description: Local development
paths:
  /component-analysis/{pkgManager}:
    post:
      operationId: componentAnalysis
      summary: Performs a vulnerability for the provided components
      parameters:
      - name: pkgManager
        in: path
        description: Package manager related to the provided packages
        required: true
        schema:
          enum:
          - maven
          type: string
        example: maven        
      - name: providers
        in: query
        description: List of vulnerability providers to get the report from
        required: false
        schema:
          enum:
          - snyk
          - tidelift
          type: string
        example: snyk
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComponentRequest'
        required: true
      responses:
        '200': 
          description: Successful component analysis report
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DependencyReport'
        '422':
          description: Invalid request
          content:
            text/plain:
              schema:
                type: string
                description: Error message
  /dependency-analysis/{pkgManager}:
    post:
      operationId: dependencyAnalysis
      summary:  Takes a client-resolved dependency graph to perform a full stack analysis from all the available Vulnerability sources
      parameters:
      - name: pkgManager
        in: path
        description: Package manager related to the provided packages
        required: true
        schema:
          enum:
          - maven
          type: string
        example: maven
      - name: providers
        in: query
        description: List of vulnerability providers to get the report from
        required: false
        schema:
          enum:
          - snyk
          - tidelift
          type: string
        example: snyk
      requestBody:
        required: true
        description: Dependency graph in DOT format
        content:
          text/vnd.graphviz:
            schema:
              type: object
      responses:
        '200':
          description: Full dependency analysis from all the available providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DependencyReport'
            text/html:
              schema:
                type: object
components:
  schemas:
    ComponentRequest:
      type: array
      items:
        $ref: '#/components/schemas/PackageRef'
      example:
        - name: io.quarkus:quarkus-jdbc-postgresql
          version: 2.13.5.Final
        - name: io.quarkus:quarkus-hibernate-orm
          version: 2.13.5.Final
    PackageRef:
      type: object
      properties:
        name:
          type: string
          description: <groupId>:<artifactId> for Java packages
          example: org.jgroups:jgroups
        version:
          type: string
          description: Package version
          example: 5.2.0.Final
      example:
        name: io.quarkus:quarkus-jdbc-postgresql
        version: 2.13.5.Final
    DependencyReport:
      type: object
      properties:
        ref:
          $ref: '#/components/schemas/PackageRef'
        issues:
          type: array
          items:
            $ref: '#/components/schemas/Issue'
        transitive:
          type: array
          items:
            $ref: '#/components/schemas/TransitiveDependencyReport'
        recommendation:
          description: Trusted Content recommendation that is not related to any security vulnerability
          $ref: '#/components/schemas/PackageRef'
        securityRecommendations:
          description: Trusted Content recommendations related to identified security vulnerabilities
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Recommendation'
      example:
        ref:
          name: io.quarkus:quarkus-jdbc-postgresql
          version: 2.13.5.Final
        issues:
          - id: SNYK-JAVA-ORGPOSTGRESQL-3146847
            source: snyk
            cves:
             - CVE-2022-41946
            rawData: {}
        transitive:
          - ref:
              name: org.postgresql:postgresql
              version: 42.5.0
            issues:
              - id: SNYK-JAVA-ORGPOSTGRESQL-3146847
                source: snyk
                cves:
                - CVE-2022-41946
                rawData: {}
        securityRecommendations:
          CVE-2022-41946:
            issueRef: CVE-2022-41946
            mavenPackage:
              name: com.fasterxml.jackson.core:jackson-databind
              version: 2.13.1.Final-redhat-00002
            productStatus: known_not_affected
    Issue:
      type: object
      properties:
        id:
          type: string
        source:
          type: string
        cves:
          type: array
          items:
            type: string
        rawData:
          type: object
      example:
        id: SNYK-JAVA-ORGPOSTGRESQL-3146847
        source: snyk
        cves:
          - CVE-2022-41946
        rawData: {}
    TransitiveDependencyReport:
      type: object
      properties:
        ref:
          $ref: '#/components/schemas/PackageRef'
        issues:
          type: array
          items:
            $ref: '#/components/schemas/Issue'
        securityRecommendations:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Recommendation'
      example:
        ref:
          name: org.postgresql:postgresql
          version: 42.5.0
        issues:
          - id: SNYK-JAVA-ORGPOSTGRESQL-3146847
            source: snyk
            cves:
             - CVE-2022-41946
            rawData: {}
    Recommendation:
      type: object
      properties:
        issueRef:
          type: string
        mavenPackage:
          $ref: '#/components/schemas/PackageRef'
        productStatus:
          type: string
      example:
        issueRef: CVE-2022-41946
        mavenPackage:
          name: io.quarkus:quarkus-jdbc-postgresql
          version: 2.13.7.Final-redhat-00003
        productStatus: fixed
